// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	api1 "github.com/enbility/eebus-go/api"
	api0 "github.com/enbility/eebus-go/usecases/api"
	"github.com/enbility/spine-go/api"
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCaCDSFInterface creates a new instance of CaCDSFInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaCDSFInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaCDSFInterface {
	mock := &CaCDSFInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CaCDSFInterface is an autogenerated mock type for the CaCDSFInterface type
type CaCDSFInterface struct {
	mock.Mock
}

type CaCDSFInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CaCDSFInterface) EXPECT() *CaCDSFInterface_Expecter {
	return &CaCDSFInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) AddFeatures() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddFeatures")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CaCDSFInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type CaCDSFInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *CaCDSFInterface_Expecter) AddFeatures() *CaCDSFInterface_AddFeatures_Call {
	return &CaCDSFInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *CaCDSFInterface_AddFeatures_Call) Run(run func()) *CaCDSFInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCDSFInterface_AddFeatures_Call) Return(err error) *CaCDSFInterface_AddFeatures_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CaCDSFInterface_AddFeatures_Call) RunAndReturn(run func() error) *CaCDSFInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) AddUseCase() {
	_mock.Called()
	return
}

// CaCDSFInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type CaCDSFInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *CaCDSFInterface_Expecter) AddUseCase() *CaCDSFInterface_AddUseCase_Call {
	return &CaCDSFInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *CaCDSFInterface_AddUseCase_Call) Run(run func()) *CaCDSFInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCDSFInterface_AddUseCase_Call) Return() *CaCDSFInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCDSFInterface_AddUseCase_Call) RunAndReturn(run func()) *CaCDSFInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// CaCDSFInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type CaCDSFInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCDSFInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *CaCDSFInterface_AvailableScenariosForEntity_Call {
	return &CaCDSFInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *CaCDSFInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCDSFInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *CaCDSFInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *CaCDSFInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *CaCDSFInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentOperationMode provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) CurrentOperationMode(entity api.EntityRemoteInterface) (api0.HvacOperationModeType, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for CurrentOperationMode")
	}

	var r0 api0.HvacOperationModeType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) (api0.HvacOperationModeType, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) api0.HvacOperationModeType); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(api0.HvacOperationModeType)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCDSFInterface_CurrentOperationMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentOperationMode'
type CaCDSFInterface_CurrentOperationMode_Call struct {
	*mock.Call
}

// CurrentOperationMode is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCDSFInterface_Expecter) CurrentOperationMode(entity interface{}) *CaCDSFInterface_CurrentOperationMode_Call {
	return &CaCDSFInterface_CurrentOperationMode_Call{Call: _e.mock.On("CurrentOperationMode", entity)}
}

func (_c *CaCDSFInterface_CurrentOperationMode_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCDSFInterface_CurrentOperationMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_CurrentOperationMode_Call) Return(hvacOperationModeType api0.HvacOperationModeType, err error) *CaCDSFInterface_CurrentOperationMode_Call {
	_c.Call.Return(hvacOperationModeType, err)
	return _c
}

func (_c *CaCDSFInterface_CurrentOperationMode_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) (api0.HvacOperationModeType, error)) *CaCDSFInterface_CurrentOperationMode_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CaCDSFInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type CaCDSFInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCDSFInterface_Expecter) IsCompatibleEntityType(entity interface{}) *CaCDSFInterface_IsCompatibleEntityType_Call {
	return &CaCDSFInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *CaCDSFInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCDSFInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_IsCompatibleEntityType_Call) Return(b bool) *CaCDSFInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CaCDSFInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *CaCDSFInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CaCDSFInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type CaCDSFInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *CaCDSFInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *CaCDSFInterface_IsScenarioAvailableAtEntity_Call {
	return &CaCDSFInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *CaCDSFInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *CaCDSFInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *CaCDSFInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CaCDSFInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *CaCDSFInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// OperationModes provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) OperationModes(entity api.EntityRemoteInterface) ([]api0.HvacOperationModeType, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for OperationModes")
	}

	var r0 []api0.HvacOperationModeType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) ([]api0.HvacOperationModeType, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []api0.HvacOperationModeType); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.HvacOperationModeType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCDSFInterface_OperationModes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OperationModes'
type CaCDSFInterface_OperationModes_Call struct {
	*mock.Call
}

// OperationModes is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCDSFInterface_Expecter) OperationModes(entity interface{}) *CaCDSFInterface_OperationModes_Call {
	return &CaCDSFInterface_OperationModes_Call{Call: _e.mock.On("OperationModes", entity)}
}

func (_c *CaCDSFInterface_OperationModes_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCDSFInterface_OperationModes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_OperationModes_Call) Return(hvacOperationModeTypes []api0.HvacOperationModeType, err error) *CaCDSFInterface_OperationModes_Call {
	_c.Call.Return(hvacOperationModeTypes, err)
	return _c
}

func (_c *CaCDSFInterface_OperationModes_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) ([]api0.HvacOperationModeType, error)) *CaCDSFInterface_OperationModes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) RemoteEntitiesScenarios() []api1.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api1.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api1.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api1.RemoteEntityScenarios)
		}
	}
	return r0
}

// CaCDSFInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type CaCDSFInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *CaCDSFInterface_Expecter) RemoteEntitiesScenarios() *CaCDSFInterface_RemoteEntitiesScenarios_Call {
	return &CaCDSFInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *CaCDSFInterface_RemoteEntitiesScenarios_Call) Run(run func()) *CaCDSFInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCDSFInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api1.RemoteEntityScenarios) *CaCDSFInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *CaCDSFInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api1.RemoteEntityScenarios) *CaCDSFInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// CaCDSFInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type CaCDSFInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *CaCDSFInterface_Expecter) RemoveUseCase() *CaCDSFInterface_RemoveUseCase_Call {
	return &CaCDSFInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *CaCDSFInterface_RemoveUseCase_Call) Run(run func()) *CaCDSFInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCDSFInterface_RemoveUseCase_Call) Return() *CaCDSFInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCDSFInterface_RemoveUseCase_Call) RunAndReturn(run func()) *CaCDSFInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// StartOneTimeDhw provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) StartOneTimeDhw(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error) {
	ret := _mock.Called(entity, resultCB)

	if len(ret) == 0 {
		panic("no return value specified for StartOneTimeDhw")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)); ok {
		return returnFunc(entity, resultCB)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) *model.MsgCounterType); ok {
		r0 = returnFunc(entity, resultCB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) error); ok {
		r1 = returnFunc(entity, resultCB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCDSFInterface_StartOneTimeDhw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOneTimeDhw'
type CaCDSFInterface_StartOneTimeDhw_Call struct {
	*mock.Call
}

// StartOneTimeDhw is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)
func (_e *CaCDSFInterface_Expecter) StartOneTimeDhw(entity interface{}, resultCB interface{}) *CaCDSFInterface_StartOneTimeDhw_Call {
	return &CaCDSFInterface_StartOneTimeDhw_Call{Call: _e.mock.On("StartOneTimeDhw", entity, resultCB)}
}

func (_c *CaCDSFInterface_StartOneTimeDhw_Call) Run(run func(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType))) *CaCDSFInterface_StartOneTimeDhw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 func(result model.ResultDataType, msgCounter model.MsgCounterType)
		if args[1] != nil {
			arg1 = args[1].(func(result model.ResultDataType, msgCounter model.MsgCounterType))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_StartOneTimeDhw_Call) Return(msgCounterType *model.MsgCounterType, err error) *CaCDSFInterface_StartOneTimeDhw_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *CaCDSFInterface_StartOneTimeDhw_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)) *CaCDSFInterface_StartOneTimeDhw_Call {
	_c.Call.Return(run)
	return _c
}

// StopOneTimeDhw provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) StopOneTimeDhw(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error) {
	ret := _mock.Called(entity, resultCB)

	if len(ret) == 0 {
		panic("no return value specified for StopOneTimeDhw")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)); ok {
		return returnFunc(entity, resultCB)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) *model.MsgCounterType); ok {
		r0 = returnFunc(entity, resultCB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface, func(result model.ResultDataType, msgCounter model.MsgCounterType)) error); ok {
		r1 = returnFunc(entity, resultCB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCDSFInterface_StopOneTimeDhw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopOneTimeDhw'
type CaCDSFInterface_StopOneTimeDhw_Call struct {
	*mock.Call
}

// StopOneTimeDhw is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)
func (_e *CaCDSFInterface_Expecter) StopOneTimeDhw(entity interface{}, resultCB interface{}) *CaCDSFInterface_StopOneTimeDhw_Call {
	return &CaCDSFInterface_StopOneTimeDhw_Call{Call: _e.mock.On("StopOneTimeDhw", entity, resultCB)}
}

func (_c *CaCDSFInterface_StopOneTimeDhw_Call) Run(run func(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType))) *CaCDSFInterface_StopOneTimeDhw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 func(result model.ResultDataType, msgCounter model.MsgCounterType)
		if args[1] != nil {
			arg1 = args[1].(func(result model.ResultDataType, msgCounter model.MsgCounterType))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_StopOneTimeDhw_Call) Return(msgCounterType *model.MsgCounterType, err error) *CaCDSFInterface_StopOneTimeDhw_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *CaCDSFInterface_StopOneTimeDhw_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)) *CaCDSFInterface_StopOneTimeDhw_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// CaCDSFInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type CaCDSFInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *CaCDSFInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *CaCDSFInterface_UpdateUseCaseAvailability_Call {
	return &CaCDSFInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *CaCDSFInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *CaCDSFInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_UpdateUseCaseAvailability_Call) Return() *CaCDSFInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCDSFInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *CaCDSFInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}

// WriteOperationMode provides a mock function for the type CaCDSFInterface
func (_mock *CaCDSFInterface) WriteOperationMode(entity api.EntityRemoteInterface, mode api0.HvacOperationModeType, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error) {
	ret := _mock.Called(entity, mode, resultCB)

	if len(ret) == 0 {
		panic("no return value specified for WriteOperationMode")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, api0.HvacOperationModeType, func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)); ok {
		return returnFunc(entity, mode, resultCB)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, api0.HvacOperationModeType, func(result model.ResultDataType, msgCounter model.MsgCounterType)) *model.MsgCounterType); ok {
		r0 = returnFunc(entity, mode, resultCB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface, api0.HvacOperationModeType, func(result model.ResultDataType, msgCounter model.MsgCounterType)) error); ok {
		r1 = returnFunc(entity, mode, resultCB)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCDSFInterface_WriteOperationMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteOperationMode'
type CaCDSFInterface_WriteOperationMode_Call struct {
	*mock.Call
}

// WriteOperationMode is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - mode api0.HvacOperationModeType
//   - resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)
func (_e *CaCDSFInterface_Expecter) WriteOperationMode(entity interface{}, mode interface{}, resultCB interface{}) *CaCDSFInterface_WriteOperationMode_Call {
	return &CaCDSFInterface_WriteOperationMode_Call{Call: _e.mock.On("WriteOperationMode", entity, mode, resultCB)}
}

func (_c *CaCDSFInterface_WriteOperationMode_Call) Run(run func(entity api.EntityRemoteInterface, mode api0.HvacOperationModeType, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType))) *CaCDSFInterface_WriteOperationMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 api0.HvacOperationModeType
		if args[1] != nil {
			arg1 = args[1].(api0.HvacOperationModeType)
		}
		var arg2 func(result model.ResultDataType, msgCounter model.MsgCounterType)
		if args[2] != nil {
			arg2 = args[2].(func(result model.ResultDataType, msgCounter model.MsgCounterType))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CaCDSFInterface_WriteOperationMode_Call) Return(msgCounterType *model.MsgCounterType, err error) *CaCDSFInterface_WriteOperationMode_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *CaCDSFInterface_WriteOperationMode_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, mode api0.HvacOperationModeType, resultCB func(result model.ResultDataType, msgCounter model.MsgCounterType)) (*model.MsgCounterType, error)) *CaCDSFInterface_WriteOperationMode_Call {
	_c.Call.Return(run)
	return _c
}
