// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	api0 "github.com/enbility/eebus-go/api"
	api1 "github.com/enbility/eebus-go/usecases/api"
	"github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewCaCRHTInterface creates a new instance of CaCRHTInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaCRHTInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaCRHTInterface {
	mock := &CaCRHTInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CaCRHTInterface is an autogenerated mock type for the CaCRHTInterface type
type CaCRHTInterface struct {
	mock.Mock
}

type CaCRHTInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CaCRHTInterface) EXPECT() *CaCRHTInterface_Expecter {
	return &CaCRHTInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) AddFeatures() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddFeatures")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CaCRHTInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type CaCRHTInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *CaCRHTInterface_Expecter) AddFeatures() *CaCRHTInterface_AddFeatures_Call {
	return &CaCRHTInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *CaCRHTInterface_AddFeatures_Call) Run(run func()) *CaCRHTInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCRHTInterface_AddFeatures_Call) Return(err error) *CaCRHTInterface_AddFeatures_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CaCRHTInterface_AddFeatures_Call) RunAndReturn(run func() error) *CaCRHTInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) AddUseCase() {
	_mock.Called()
	return
}

// CaCRHTInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type CaCRHTInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *CaCRHTInterface_Expecter) AddUseCase() *CaCRHTInterface_AddUseCase_Call {
	return &CaCRHTInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *CaCRHTInterface_AddUseCase_Call) Run(run func()) *CaCRHTInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCRHTInterface_AddUseCase_Call) Return() *CaCRHTInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCRHTInterface_AddUseCase_Call) RunAndReturn(run func()) *CaCRHTInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// CaCRHTInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type CaCRHTInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCRHTInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *CaCRHTInterface_AvailableScenariosForEntity_Call {
	return &CaCRHTInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *CaCRHTInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCRHTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *CaCRHTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *CaCRHTInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *CaCRHTInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CaCRHTInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type CaCRHTInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCRHTInterface_Expecter) IsCompatibleEntityType(entity interface{}) *CaCRHTInterface_IsCompatibleEntityType_Call {
	return &CaCRHTInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *CaCRHTInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCRHTInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_IsCompatibleEntityType_Call) Return(b bool) *CaCRHTInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CaCRHTInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *CaCRHTInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CaCRHTInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type CaCRHTInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *CaCRHTInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *CaCRHTInterface_IsScenarioAvailableAtEntity_Call {
	return &CaCRHTInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *CaCRHTInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *CaCRHTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *CaCRHTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CaCRHTInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *CaCRHTInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) RemoteEntitiesScenarios() []api0.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api0.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api0.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.RemoteEntityScenarios)
		}
	}
	return r0
}

// CaCRHTInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type CaCRHTInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *CaCRHTInterface_Expecter) RemoteEntitiesScenarios() *CaCRHTInterface_RemoteEntitiesScenarios_Call {
	return &CaCRHTInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *CaCRHTInterface_RemoteEntitiesScenarios_Call) Run(run func()) *CaCRHTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCRHTInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api0.RemoteEntityScenarios) *CaCRHTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *CaCRHTInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api0.RemoteEntityScenarios) *CaCRHTInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// CaCRHTInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type CaCRHTInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *CaCRHTInterface_Expecter) RemoveUseCase() *CaCRHTInterface_RemoveUseCase_Call {
	return &CaCRHTInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *CaCRHTInterface_RemoveUseCase_Call) Run(run func()) *CaCRHTInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CaCRHTInterface_RemoveUseCase_Call) Return() *CaCRHTInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCRHTInterface_RemoveUseCase_Call) RunAndReturn(run func()) *CaCRHTInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// SetpointConstraints provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) SetpointConstraints(entity api.EntityRemoteInterface) ([]api1.SetpointConstraints, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for SetpointConstraints")
	}

	var r0 []api1.SetpointConstraints
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) ([]api1.SetpointConstraints, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []api1.SetpointConstraints); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api1.SetpointConstraints)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCRHTInterface_SetpointConstraints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetpointConstraints'
type CaCRHTInterface_SetpointConstraints_Call struct {
	*mock.Call
}

// SetpointConstraints is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCRHTInterface_Expecter) SetpointConstraints(entity interface{}) *CaCRHTInterface_SetpointConstraints_Call {
	return &CaCRHTInterface_SetpointConstraints_Call{Call: _e.mock.On("SetpointConstraints", entity)}
}

func (_c *CaCRHTInterface_SetpointConstraints_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCRHTInterface_SetpointConstraints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_SetpointConstraints_Call) Return(setpointConstraintss []api1.SetpointConstraints, err error) *CaCRHTInterface_SetpointConstraints_Call {
	_c.Call.Return(setpointConstraintss, err)
	return _c
}

func (_c *CaCRHTInterface_SetpointConstraints_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) ([]api1.SetpointConstraints, error)) *CaCRHTInterface_SetpointConstraints_Call {
	_c.Call.Return(run)
	return _c
}

// Setpoints provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) Setpoints(entity api.EntityRemoteInterface) ([]api1.Setpoint, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Setpoints")
	}

	var r0 []api1.Setpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) ([]api1.Setpoint, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []api1.Setpoint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api1.Setpoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CaCRHTInterface_Setpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setpoints'
type CaCRHTInterface_Setpoints_Call struct {
	*mock.Call
}

// Setpoints is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CaCRHTInterface_Expecter) Setpoints(entity interface{}) *CaCRHTInterface_Setpoints_Call {
	return &CaCRHTInterface_Setpoints_Call{Call: _e.mock.On("Setpoints", entity)}
}

func (_c *CaCRHTInterface_Setpoints_Call) Run(run func(entity api.EntityRemoteInterface)) *CaCRHTInterface_Setpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_Setpoints_Call) Return(setpoints []api1.Setpoint, err error) *CaCRHTInterface_Setpoints_Call {
	_c.Call.Return(setpoints, err)
	return _c
}

func (_c *CaCRHTInterface_Setpoints_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) ([]api1.Setpoint, error)) *CaCRHTInterface_Setpoints_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// CaCRHTInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type CaCRHTInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *CaCRHTInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *CaCRHTInterface_UpdateUseCaseAvailability_Call {
	return &CaCRHTInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *CaCRHTInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *CaCRHTInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_UpdateUseCaseAvailability_Call) Return() *CaCRHTInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *CaCRHTInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *CaCRHTInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}

// WriteSetpoint provides a mock function for the type CaCRHTInterface
func (_mock *CaCRHTInterface) WriteSetpoint(entity api.EntityRemoteInterface, mode api1.HvacOperationModeType, degC float64) error {
	ret := _mock.Called(entity, mode, degC)

	if len(ret) == 0 {
		panic("no return value specified for WriteSetpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, api1.HvacOperationModeType, float64) error); ok {
		r0 = returnFunc(entity, mode, degC)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CaCRHTInterface_WriteSetpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSetpoint'
type CaCRHTInterface_WriteSetpoint_Call struct {
	*mock.Call
}

// WriteSetpoint is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - mode api1.HvacOperationModeType
//   - degC float64
func (_e *CaCRHTInterface_Expecter) WriteSetpoint(entity interface{}, mode interface{}, degC interface{}) *CaCRHTInterface_WriteSetpoint_Call {
	return &CaCRHTInterface_WriteSetpoint_Call{Call: _e.mock.On("WriteSetpoint", entity, mode, degC)}
}

func (_c *CaCRHTInterface_WriteSetpoint_Call) Run(run func(entity api.EntityRemoteInterface, mode api1.HvacOperationModeType, degC float64)) *CaCRHTInterface_WriteSetpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 api1.HvacOperationModeType
		if args[1] != nil {
			arg1 = args[1].(api1.HvacOperationModeType)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CaCRHTInterface_WriteSetpoint_Call) Return(err error) *CaCRHTInterface_WriteSetpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CaCRHTInterface_WriteSetpoint_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, mode api1.HvacOperationModeType, degC float64) error) *CaCRHTInterface_WriteSetpoint_Call {
	_c.Call.Return(run)
	return _c
}
