// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	api0 "github.com/enbility/eebus-go/api"
	"github.com/enbility/spine-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewCemVAPDInterface creates a new instance of CemVAPDInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCemVAPDInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CemVAPDInterface {
	mock := &CemVAPDInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CemVAPDInterface is an autogenerated mock type for the CemVAPDInterface type
type CemVAPDInterface struct {
	mock.Mock
}

type CemVAPDInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CemVAPDInterface) EXPECT() *CemVAPDInterface_Expecter {
	return &CemVAPDInterface_Expecter{mock: &_m.Mock}
}

// AddFeatures provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) AddFeatures() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddFeatures")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CemVAPDInterface_AddFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeatures'
type CemVAPDInterface_AddFeatures_Call struct {
	*mock.Call
}

// AddFeatures is a helper method to define mock.On call
func (_e *CemVAPDInterface_Expecter) AddFeatures() *CemVAPDInterface_AddFeatures_Call {
	return &CemVAPDInterface_AddFeatures_Call{Call: _e.mock.On("AddFeatures")}
}

func (_c *CemVAPDInterface_AddFeatures_Call) Run(run func()) *CemVAPDInterface_AddFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CemVAPDInterface_AddFeatures_Call) Return(err error) *CemVAPDInterface_AddFeatures_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CemVAPDInterface_AddFeatures_Call) RunAndReturn(run func() error) *CemVAPDInterface_AddFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddUseCase provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) AddUseCase() {
	_mock.Called()
	return
}

// CemVAPDInterface_AddUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUseCase'
type CemVAPDInterface_AddUseCase_Call struct {
	*mock.Call
}

// AddUseCase is a helper method to define mock.On call
func (_e *CemVAPDInterface_Expecter) AddUseCase() *CemVAPDInterface_AddUseCase_Call {
	return &CemVAPDInterface_AddUseCase_Call{Call: _e.mock.On("AddUseCase")}
}

func (_c *CemVAPDInterface_AddUseCase_Call) Run(run func()) *CemVAPDInterface_AddUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CemVAPDInterface_AddUseCase_Call) Return() *CemVAPDInterface_AddUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CemVAPDInterface_AddUseCase_Call) RunAndReturn(run func()) *CemVAPDInterface_AddUseCase_Call {
	_c.Run(run)
	return _c
}

// AvailableScenariosForEntity provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) AvailableScenariosForEntity(entity api.EntityRemoteInterface) []uint {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for AvailableScenariosForEntity")
	}

	var r0 []uint
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) []uint); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}
	return r0
}

// CemVAPDInterface_AvailableScenariosForEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailableScenariosForEntity'
type CemVAPDInterface_AvailableScenariosForEntity_Call struct {
	*mock.Call
}

// AvailableScenariosForEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CemVAPDInterface_Expecter) AvailableScenariosForEntity(entity interface{}) *CemVAPDInterface_AvailableScenariosForEntity_Call {
	return &CemVAPDInterface_AvailableScenariosForEntity_Call{Call: _e.mock.On("AvailableScenariosForEntity", entity)}
}

func (_c *CemVAPDInterface_AvailableScenariosForEntity_Call) Run(run func(entity api.EntityRemoteInterface)) *CemVAPDInterface_AvailableScenariosForEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_AvailableScenariosForEntity_Call) Return(uints []uint) *CemVAPDInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(uints)
	return _c
}

func (_c *CemVAPDInterface_AvailableScenariosForEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) []uint) *CemVAPDInterface_AvailableScenariosForEntity_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleEntityType provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) IsCompatibleEntityType(entity api.EntityRemoteInterface) bool {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleEntityType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) bool); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CemVAPDInterface_IsCompatibleEntityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleEntityType'
type CemVAPDInterface_IsCompatibleEntityType_Call struct {
	*mock.Call
}

// IsCompatibleEntityType is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CemVAPDInterface_Expecter) IsCompatibleEntityType(entity interface{}) *CemVAPDInterface_IsCompatibleEntityType_Call {
	return &CemVAPDInterface_IsCompatibleEntityType_Call{Call: _e.mock.On("IsCompatibleEntityType", entity)}
}

func (_c *CemVAPDInterface_IsCompatibleEntityType_Call) Run(run func(entity api.EntityRemoteInterface)) *CemVAPDInterface_IsCompatibleEntityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_IsCompatibleEntityType_Call) Return(b bool) *CemVAPDInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CemVAPDInterface_IsCompatibleEntityType_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) bool) *CemVAPDInterface_IsCompatibleEntityType_Call {
	_c.Call.Return(run)
	return _c
}

// IsScenarioAvailableAtEntity provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) IsScenarioAvailableAtEntity(entity api.EntityRemoteInterface, scenario uint) bool {
	ret := _mock.Called(entity, scenario)

	if len(ret) == 0 {
		panic("no return value specified for IsScenarioAvailableAtEntity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface, uint) bool); ok {
		r0 = returnFunc(entity, scenario)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CemVAPDInterface_IsScenarioAvailableAtEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsScenarioAvailableAtEntity'
type CemVAPDInterface_IsScenarioAvailableAtEntity_Call struct {
	*mock.Call
}

// IsScenarioAvailableAtEntity is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
//   - scenario uint
func (_e *CemVAPDInterface_Expecter) IsScenarioAvailableAtEntity(entity interface{}, scenario interface{}) *CemVAPDInterface_IsScenarioAvailableAtEntity_Call {
	return &CemVAPDInterface_IsScenarioAvailableAtEntity_Call{Call: _e.mock.On("IsScenarioAvailableAtEntity", entity, scenario)}
}

func (_c *CemVAPDInterface_IsScenarioAvailableAtEntity_Call) Run(run func(entity api.EntityRemoteInterface, scenario uint)) *CemVAPDInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_IsScenarioAvailableAtEntity_Call) Return(b bool) *CemVAPDInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *CemVAPDInterface_IsScenarioAvailableAtEntity_Call) RunAndReturn(run func(entity api.EntityRemoteInterface, scenario uint) bool) *CemVAPDInterface_IsScenarioAvailableAtEntity_Call {
	_c.Call.Return(run)
	return _c
}

// PVYieldTotal provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) PVYieldTotal(entity api.EntityRemoteInterface) (float64, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for PVYieldTotal")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CemVAPDInterface_PVYieldTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PVYieldTotal'
type CemVAPDInterface_PVYieldTotal_Call struct {
	*mock.Call
}

// PVYieldTotal is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CemVAPDInterface_Expecter) PVYieldTotal(entity interface{}) *CemVAPDInterface_PVYieldTotal_Call {
	return &CemVAPDInterface_PVYieldTotal_Call{Call: _e.mock.On("PVYieldTotal", entity)}
}

func (_c *CemVAPDInterface_PVYieldTotal_Call) Run(run func(entity api.EntityRemoteInterface)) *CemVAPDInterface_PVYieldTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_PVYieldTotal_Call) Return(f float64, err error) *CemVAPDInterface_PVYieldTotal_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *CemVAPDInterface_PVYieldTotal_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) (float64, error)) *CemVAPDInterface_PVYieldTotal_Call {
	_c.Call.Return(run)
	return _c
}

// Power provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) Power(entity api.EntityRemoteInterface) (float64, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for Power")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CemVAPDInterface_Power_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Power'
type CemVAPDInterface_Power_Call struct {
	*mock.Call
}

// Power is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CemVAPDInterface_Expecter) Power(entity interface{}) *CemVAPDInterface_Power_Call {
	return &CemVAPDInterface_Power_Call{Call: _e.mock.On("Power", entity)}
}

func (_c *CemVAPDInterface_Power_Call) Run(run func(entity api.EntityRemoteInterface)) *CemVAPDInterface_Power_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_Power_Call) Return(f float64, err error) *CemVAPDInterface_Power_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *CemVAPDInterface_Power_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) (float64, error)) *CemVAPDInterface_Power_Call {
	_c.Call.Return(run)
	return _c
}

// PowerNominalPeak provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) PowerNominalPeak(entity api.EntityRemoteInterface) (float64, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for PowerNominalPeak")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) (float64, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EntityRemoteInterface) float64); ok {
		r0 = returnFunc(entity)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EntityRemoteInterface) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CemVAPDInterface_PowerNominalPeak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PowerNominalPeak'
type CemVAPDInterface_PowerNominalPeak_Call struct {
	*mock.Call
}

// PowerNominalPeak is a helper method to define mock.On call
//   - entity api.EntityRemoteInterface
func (_e *CemVAPDInterface_Expecter) PowerNominalPeak(entity interface{}) *CemVAPDInterface_PowerNominalPeak_Call {
	return &CemVAPDInterface_PowerNominalPeak_Call{Call: _e.mock.On("PowerNominalPeak", entity)}
}

func (_c *CemVAPDInterface_PowerNominalPeak_Call) Run(run func(entity api.EntityRemoteInterface)) *CemVAPDInterface_PowerNominalPeak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EntityRemoteInterface
		if args[0] != nil {
			arg0 = args[0].(api.EntityRemoteInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_PowerNominalPeak_Call) Return(f float64, err error) *CemVAPDInterface_PowerNominalPeak_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *CemVAPDInterface_PowerNominalPeak_Call) RunAndReturn(run func(entity api.EntityRemoteInterface) (float64, error)) *CemVAPDInterface_PowerNominalPeak_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteEntitiesScenarios provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) RemoteEntitiesScenarios() []api0.RemoteEntityScenarios {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteEntitiesScenarios")
	}

	var r0 []api0.RemoteEntityScenarios
	if returnFunc, ok := ret.Get(0).(func() []api0.RemoteEntityScenarios); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api0.RemoteEntityScenarios)
		}
	}
	return r0
}

// CemVAPDInterface_RemoteEntitiesScenarios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteEntitiesScenarios'
type CemVAPDInterface_RemoteEntitiesScenarios_Call struct {
	*mock.Call
}

// RemoteEntitiesScenarios is a helper method to define mock.On call
func (_e *CemVAPDInterface_Expecter) RemoteEntitiesScenarios() *CemVAPDInterface_RemoteEntitiesScenarios_Call {
	return &CemVAPDInterface_RemoteEntitiesScenarios_Call{Call: _e.mock.On("RemoteEntitiesScenarios")}
}

func (_c *CemVAPDInterface_RemoteEntitiesScenarios_Call) Run(run func()) *CemVAPDInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CemVAPDInterface_RemoteEntitiesScenarios_Call) Return(remoteEntityScenarioss []api0.RemoteEntityScenarios) *CemVAPDInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(remoteEntityScenarioss)
	return _c
}

func (_c *CemVAPDInterface_RemoteEntitiesScenarios_Call) RunAndReturn(run func() []api0.RemoteEntityScenarios) *CemVAPDInterface_RemoteEntitiesScenarios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUseCase provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) RemoveUseCase() {
	_mock.Called()
	return
}

// CemVAPDInterface_RemoveUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUseCase'
type CemVAPDInterface_RemoveUseCase_Call struct {
	*mock.Call
}

// RemoveUseCase is a helper method to define mock.On call
func (_e *CemVAPDInterface_Expecter) RemoveUseCase() *CemVAPDInterface_RemoveUseCase_Call {
	return &CemVAPDInterface_RemoveUseCase_Call{Call: _e.mock.On("RemoveUseCase")}
}

func (_c *CemVAPDInterface_RemoveUseCase_Call) Run(run func()) *CemVAPDInterface_RemoveUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CemVAPDInterface_RemoveUseCase_Call) Return() *CemVAPDInterface_RemoveUseCase_Call {
	_c.Call.Return()
	return _c
}

func (_c *CemVAPDInterface_RemoveUseCase_Call) RunAndReturn(run func()) *CemVAPDInterface_RemoveUseCase_Call {
	_c.Run(run)
	return _c
}

// UpdateUseCaseAvailability provides a mock function for the type CemVAPDInterface
func (_mock *CemVAPDInterface) UpdateUseCaseAvailability(available bool) {
	_mock.Called(available)
	return
}

// CemVAPDInterface_UpdateUseCaseAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUseCaseAvailability'
type CemVAPDInterface_UpdateUseCaseAvailability_Call struct {
	*mock.Call
}

// UpdateUseCaseAvailability is a helper method to define mock.On call
//   - available bool
func (_e *CemVAPDInterface_Expecter) UpdateUseCaseAvailability(available interface{}) *CemVAPDInterface_UpdateUseCaseAvailability_Call {
	return &CemVAPDInterface_UpdateUseCaseAvailability_Call{Call: _e.mock.On("UpdateUseCaseAvailability", available)}
}

func (_c *CemVAPDInterface_UpdateUseCaseAvailability_Call) Run(run func(available bool)) *CemVAPDInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CemVAPDInterface_UpdateUseCaseAvailability_Call) Return() *CemVAPDInterface_UpdateUseCaseAvailability_Call {
	_c.Call.Return()
	return _c
}

func (_c *CemVAPDInterface_UpdateUseCaseAvailability_Call) RunAndReturn(run func(available bool)) *CemVAPDInterface_UpdateUseCaseAvailability_Call {
	_c.Run(run)
	return _c
}
