// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUpdateData creates a new instance of UpdateData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateData(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateData {
	mock := &UpdateData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UpdateData is an autogenerated mock type for the UpdateData type
type UpdateData struct {
	mock.Mock
}

type UpdateData_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateData) EXPECT() *UpdateData_Expecter {
	return &UpdateData_Expecter{mock: &_m.Mock}
}

// NotSupportedError provides a mock function for the type UpdateData
func (_mock *UpdateData) NotSupportedError() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotSupportedError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UpdateData_NotSupportedError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotSupportedError'
type UpdateData_NotSupportedError_Call struct {
	*mock.Call
}

// NotSupportedError is a helper method to define mock.On call
func (_e *UpdateData_Expecter) NotSupportedError() *UpdateData_NotSupportedError_Call {
	return &UpdateData_NotSupportedError_Call{Call: _e.mock.On("NotSupportedError")}
}

func (_c *UpdateData_NotSupportedError_Call) Run(run func()) *UpdateData_NotSupportedError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateData_NotSupportedError_Call) Return(err error) *UpdateData_NotSupportedError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UpdateData_NotSupportedError_Call) RunAndReturn(run func() error) *UpdateData_NotSupportedError_Call {
	_c.Call.Return(run)
	return _c
}

// Supported provides a mock function for the type UpdateData
func (_mock *UpdateData) Supported() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Supported")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// UpdateData_Supported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supported'
type UpdateData_Supported_Call struct {
	*mock.Call
}

// Supported is a helper method to define mock.On call
func (_e *UpdateData_Expecter) Supported() *UpdateData_Supported_Call {
	return &UpdateData_Supported_Call{Call: _e.mock.On("Supported")}
}

func (_c *UpdateData_Supported_Call) Run(run func()) *UpdateData_Supported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UpdateData_Supported_Call) Return(b bool) *UpdateData_Supported_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *UpdateData_Supported_Call) RunAndReturn(run func() bool) *UpdateData_Supported_Call {
	_c.Call.Return(run)
	return _c
}
