// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDeviceClassificationCommonInterface creates a new instance of DeviceClassificationCommonInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceClassificationCommonInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceClassificationCommonInterface {
	mock := &DeviceClassificationCommonInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeviceClassificationCommonInterface is an autogenerated mock type for the DeviceClassificationCommonInterface type
type DeviceClassificationCommonInterface struct {
	mock.Mock
}

type DeviceClassificationCommonInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DeviceClassificationCommonInterface) EXPECT() *DeviceClassificationCommonInterface_Expecter {
	return &DeviceClassificationCommonInterface_Expecter{mock: &_m.Mock}
}

// GetManufacturerDetails provides a mock function for the type DeviceClassificationCommonInterface
func (_mock *DeviceClassificationCommonInterface) GetManufacturerDetails() (*model.DeviceClassificationManufacturerDataType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetManufacturerDetails")
	}

	var r0 *model.DeviceClassificationManufacturerDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.DeviceClassificationManufacturerDataType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.DeviceClassificationManufacturerDataType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeviceClassificationManufacturerDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceClassificationCommonInterface_GetManufacturerDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManufacturerDetails'
type DeviceClassificationCommonInterface_GetManufacturerDetails_Call struct {
	*mock.Call
}

// GetManufacturerDetails is a helper method to define mock.On call
func (_e *DeviceClassificationCommonInterface_Expecter) GetManufacturerDetails() *DeviceClassificationCommonInterface_GetManufacturerDetails_Call {
	return &DeviceClassificationCommonInterface_GetManufacturerDetails_Call{Call: _e.mock.On("GetManufacturerDetails")}
}

func (_c *DeviceClassificationCommonInterface_GetManufacturerDetails_Call) Run(run func()) *DeviceClassificationCommonInterface_GetManufacturerDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceClassificationCommonInterface_GetManufacturerDetails_Call) Return(deviceClassificationManufacturerDataType *model.DeviceClassificationManufacturerDataType, err error) *DeviceClassificationCommonInterface_GetManufacturerDetails_Call {
	_c.Call.Return(deviceClassificationManufacturerDataType, err)
	return _c
}

func (_c *DeviceClassificationCommonInterface_GetManufacturerDetails_Call) RunAndReturn(run func() (*model.DeviceClassificationManufacturerDataType, error)) *DeviceClassificationCommonInterface_GetManufacturerDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserData provides a mock function for the type DeviceClassificationCommonInterface
func (_mock *DeviceClassificationCommonInterface) GetUserData() (*model.DeviceClassificationUserDataType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserData")
	}

	var r0 *model.DeviceClassificationUserDataType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.DeviceClassificationUserDataType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.DeviceClassificationUserDataType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeviceClassificationUserDataType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceClassificationCommonInterface_GetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserData'
type DeviceClassificationCommonInterface_GetUserData_Call struct {
	*mock.Call
}

// GetUserData is a helper method to define mock.On call
func (_e *DeviceClassificationCommonInterface_Expecter) GetUserData() *DeviceClassificationCommonInterface_GetUserData_Call {
	return &DeviceClassificationCommonInterface_GetUserData_Call{Call: _e.mock.On("GetUserData")}
}

func (_c *DeviceClassificationCommonInterface_GetUserData_Call) Run(run func()) *DeviceClassificationCommonInterface_GetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceClassificationCommonInterface_GetUserData_Call) Return(deviceClassificationUserDataType *model.DeviceClassificationUserDataType, err error) *DeviceClassificationCommonInterface_GetUserData_Call {
	_c.Call.Return(deviceClassificationUserDataType, err)
	return _c
}

func (_c *DeviceClassificationCommonInterface_GetUserData_Call) RunAndReturn(run func() (*model.DeviceClassificationUserDataType, error)) *DeviceClassificationCommonInterface_GetUserData_Call {
	_c.Call.Return(run)
	return _c
}
