// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/spine-go/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDeviceClassificationClientInterface creates a new instance of DeviceClassificationClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceClassificationClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceClassificationClientInterface {
	mock := &DeviceClassificationClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DeviceClassificationClientInterface is an autogenerated mock type for the DeviceClassificationClientInterface type
type DeviceClassificationClientInterface struct {
	mock.Mock
}

type DeviceClassificationClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DeviceClassificationClientInterface) EXPECT() *DeviceClassificationClientInterface_Expecter {
	return &DeviceClassificationClientInterface_Expecter{mock: &_m.Mock}
}

// RequestManufacturerDetails provides a mock function for the type DeviceClassificationClientInterface
func (_mock *DeviceClassificationClientInterface) RequestManufacturerDetails() (*model.MsgCounterType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestManufacturerDetails")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.MsgCounterType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.MsgCounterType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceClassificationClientInterface_RequestManufacturerDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestManufacturerDetails'
type DeviceClassificationClientInterface_RequestManufacturerDetails_Call struct {
	*mock.Call
}

// RequestManufacturerDetails is a helper method to define mock.On call
func (_e *DeviceClassificationClientInterface_Expecter) RequestManufacturerDetails() *DeviceClassificationClientInterface_RequestManufacturerDetails_Call {
	return &DeviceClassificationClientInterface_RequestManufacturerDetails_Call{Call: _e.mock.On("RequestManufacturerDetails")}
}

func (_c *DeviceClassificationClientInterface_RequestManufacturerDetails_Call) Run(run func()) *DeviceClassificationClientInterface_RequestManufacturerDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceClassificationClientInterface_RequestManufacturerDetails_Call) Return(msgCounterType *model.MsgCounterType, err error) *DeviceClassificationClientInterface_RequestManufacturerDetails_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *DeviceClassificationClientInterface_RequestManufacturerDetails_Call) RunAndReturn(run func() (*model.MsgCounterType, error)) *DeviceClassificationClientInterface_RequestManufacturerDetails_Call {
	_c.Call.Return(run)
	return _c
}

// RequestUserData provides a mock function for the type DeviceClassificationClientInterface
func (_mock *DeviceClassificationClientInterface) RequestUserData() (*model.MsgCounterType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestUserData")
	}

	var r0 *model.MsgCounterType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.MsgCounterType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.MsgCounterType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DeviceClassificationClientInterface_RequestUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestUserData'
type DeviceClassificationClientInterface_RequestUserData_Call struct {
	*mock.Call
}

// RequestUserData is a helper method to define mock.On call
func (_e *DeviceClassificationClientInterface_Expecter) RequestUserData() *DeviceClassificationClientInterface_RequestUserData_Call {
	return &DeviceClassificationClientInterface_RequestUserData_Call{Call: _e.mock.On("RequestUserData")}
}

func (_c *DeviceClassificationClientInterface_RequestUserData_Call) Run(run func()) *DeviceClassificationClientInterface_RequestUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeviceClassificationClientInterface_RequestUserData_Call) Return(msgCounterType *model.MsgCounterType, err error) *DeviceClassificationClientInterface_RequestUserData_Call {
	_c.Call.Return(msgCounterType, err)
	return _c
}

func (_c *DeviceClassificationClientInterface_RequestUserData_Call) RunAndReturn(run func() (*model.MsgCounterType, error)) *DeviceClassificationClientInterface_RequestUserData_Call {
	_c.Call.Return(run)
	return _c
}
