// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	api "github.com/enbility/eebus-go/api"
	mock "github.com/stretchr/testify/mock"

	ship_goapi "github.com/enbility/ship-go/api"
)

// EEBUSServiceHandler is an autogenerated mock type for the EEBUSServiceHandler type
type EEBUSServiceHandler struct {
	mock.Mock
}

type EEBUSServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *EEBUSServiceHandler) EXPECT() *EEBUSServiceHandler_Expecter {
	return &EEBUSServiceHandler_Expecter{mock: &_m.Mock}
}

// AllowWaitingForTrust provides a mock function with given fields: ski
func (_m *EEBUSServiceHandler) AllowWaitingForTrust(ski string) bool {
	ret := _m.Called(ski)

	if len(ret) == 0 {
		panic("no return value specified for AllowWaitingForTrust")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ski)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// EEBUSServiceHandler_AllowWaitingForTrust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowWaitingForTrust'
type EEBUSServiceHandler_AllowWaitingForTrust_Call struct {
	*mock.Call
}

// AllowWaitingForTrust is a helper method to define mock.On call
//   - ski string
func (_e *EEBUSServiceHandler_Expecter) AllowWaitingForTrust(ski interface{}) *EEBUSServiceHandler_AllowWaitingForTrust_Call {
	return &EEBUSServiceHandler_AllowWaitingForTrust_Call{Call: _e.mock.On("AllowWaitingForTrust", ski)}
}

func (_c *EEBUSServiceHandler_AllowWaitingForTrust_Call) Run(run func(ski string)) *EEBUSServiceHandler_AllowWaitingForTrust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EEBUSServiceHandler_AllowWaitingForTrust_Call) Return(_a0 bool) *EEBUSServiceHandler_AllowWaitingForTrust_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EEBUSServiceHandler_AllowWaitingForTrust_Call) RunAndReturn(run func(string) bool) *EEBUSServiceHandler_AllowWaitingForTrust_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSKIConnected provides a mock function with given fields: service, ski
func (_m *EEBUSServiceHandler) RemoteSKIConnected(service api.EEBUSService, ski string) {
	_m.Called(service, ski)
}

// EEBUSServiceHandler_RemoteSKIConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIConnected'
type EEBUSServiceHandler_RemoteSKIConnected_Call struct {
	*mock.Call
}

// RemoteSKIConnected is a helper method to define mock.On call
//   - service api.EEBUSService
//   - ski string
func (_e *EEBUSServiceHandler_Expecter) RemoteSKIConnected(service interface{}, ski interface{}) *EEBUSServiceHandler_RemoteSKIConnected_Call {
	return &EEBUSServiceHandler_RemoteSKIConnected_Call{Call: _e.mock.On("RemoteSKIConnected", service, ski)}
}

func (_c *EEBUSServiceHandler_RemoteSKIConnected_Call) Run(run func(service api.EEBUSService, ski string)) *EEBUSServiceHandler_RemoteSKIConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EEBUSService), args[1].(string))
	})
	return _c
}

func (_c *EEBUSServiceHandler_RemoteSKIConnected_Call) Return() *EEBUSServiceHandler_RemoteSKIConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *EEBUSServiceHandler_RemoteSKIConnected_Call) RunAndReturn(run func(api.EEBUSService, string)) *EEBUSServiceHandler_RemoteSKIConnected_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteSKIDisconnected provides a mock function with given fields: service, ski
func (_m *EEBUSServiceHandler) RemoteSKIDisconnected(service api.EEBUSService, ski string) {
	_m.Called(service, ski)
}

// EEBUSServiceHandler_RemoteSKIDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteSKIDisconnected'
type EEBUSServiceHandler_RemoteSKIDisconnected_Call struct {
	*mock.Call
}

// RemoteSKIDisconnected is a helper method to define mock.On call
//   - service api.EEBUSService
//   - ski string
func (_e *EEBUSServiceHandler_Expecter) RemoteSKIDisconnected(service interface{}, ski interface{}) *EEBUSServiceHandler_RemoteSKIDisconnected_Call {
	return &EEBUSServiceHandler_RemoteSKIDisconnected_Call{Call: _e.mock.On("RemoteSKIDisconnected", service, ski)}
}

func (_c *EEBUSServiceHandler_RemoteSKIDisconnected_Call) Run(run func(service api.EEBUSService, ski string)) *EEBUSServiceHandler_RemoteSKIDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EEBUSService), args[1].(string))
	})
	return _c
}

func (_c *EEBUSServiceHandler_RemoteSKIDisconnected_Call) Return() *EEBUSServiceHandler_RemoteSKIDisconnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *EEBUSServiceHandler_RemoteSKIDisconnected_Call) RunAndReturn(run func(api.EEBUSService, string)) *EEBUSServiceHandler_RemoteSKIDisconnected_Call {
	_c.Call.Return(run)
	return _c
}

// ServicePairingDetailUpdate provides a mock function with given fields: ski, detail
func (_m *EEBUSServiceHandler) ServicePairingDetailUpdate(ski string, detail *ship_goapi.ConnectionStateDetail) {
	_m.Called(ski, detail)
}

// EEBUSServiceHandler_ServicePairingDetailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServicePairingDetailUpdate'
type EEBUSServiceHandler_ServicePairingDetailUpdate_Call struct {
	*mock.Call
}

// ServicePairingDetailUpdate is a helper method to define mock.On call
//   - ski string
//   - detail *ship_goapi.ConnectionStateDetail
func (_e *EEBUSServiceHandler_Expecter) ServicePairingDetailUpdate(ski interface{}, detail interface{}) *EEBUSServiceHandler_ServicePairingDetailUpdate_Call {
	return &EEBUSServiceHandler_ServicePairingDetailUpdate_Call{Call: _e.mock.On("ServicePairingDetailUpdate", ski, detail)}
}

func (_c *EEBUSServiceHandler_ServicePairingDetailUpdate_Call) Run(run func(ski string, detail *ship_goapi.ConnectionStateDetail)) *EEBUSServiceHandler_ServicePairingDetailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*ship_goapi.ConnectionStateDetail))
	})
	return _c
}

func (_c *EEBUSServiceHandler_ServicePairingDetailUpdate_Call) Return() *EEBUSServiceHandler_ServicePairingDetailUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *EEBUSServiceHandler_ServicePairingDetailUpdate_Call) RunAndReturn(run func(string, *ship_goapi.ConnectionStateDetail)) *EEBUSServiceHandler_ServicePairingDetailUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceShipIDUpdate provides a mock function with given fields: ski, shipdID
func (_m *EEBUSServiceHandler) ServiceShipIDUpdate(ski string, shipdID string) {
	_m.Called(ski, shipdID)
}

// EEBUSServiceHandler_ServiceShipIDUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceShipIDUpdate'
type EEBUSServiceHandler_ServiceShipIDUpdate_Call struct {
	*mock.Call
}

// ServiceShipIDUpdate is a helper method to define mock.On call
//   - ski string
//   - shipdID string
func (_e *EEBUSServiceHandler_Expecter) ServiceShipIDUpdate(ski interface{}, shipdID interface{}) *EEBUSServiceHandler_ServiceShipIDUpdate_Call {
	return &EEBUSServiceHandler_ServiceShipIDUpdate_Call{Call: _e.mock.On("ServiceShipIDUpdate", ski, shipdID)}
}

func (_c *EEBUSServiceHandler_ServiceShipIDUpdate_Call) Run(run func(ski string, shipdID string)) *EEBUSServiceHandler_ServiceShipIDUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *EEBUSServiceHandler_ServiceShipIDUpdate_Call) Return() *EEBUSServiceHandler_ServiceShipIDUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *EEBUSServiceHandler_ServiceShipIDUpdate_Call) RunAndReturn(run func(string, string)) *EEBUSServiceHandler_ServiceShipIDUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// VisibleRemoteServicesUpdated provides a mock function with given fields: service, entries
func (_m *EEBUSServiceHandler) VisibleRemoteServicesUpdated(service api.EEBUSService, entries []ship_goapi.RemoteService) {
	_m.Called(service, entries)
}

// EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisibleRemoteServicesUpdated'
type EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call struct {
	*mock.Call
}

// VisibleRemoteServicesUpdated is a helper method to define mock.On call
//   - service api.EEBUSService
//   - entries []ship_goapi.RemoteService
func (_e *EEBUSServiceHandler_Expecter) VisibleRemoteServicesUpdated(service interface{}, entries interface{}) *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call {
	return &EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call{Call: _e.mock.On("VisibleRemoteServicesUpdated", service, entries)}
}

func (_c *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call) Run(run func(service api.EEBUSService, entries []ship_goapi.RemoteService)) *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.EEBUSService), args[1].([]ship_goapi.RemoteService))
	})
	return _c
}

func (_c *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call) Return() *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call {
	_c.Call.Return()
	return _c
}

func (_c *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call) RunAndReturn(run func(api.EEBUSService, []ship_goapi.RemoteService)) *EEBUSServiceHandler_VisibleRemoteServicesUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewEEBUSServiceHandler creates a new instance of EEBUSServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEEBUSServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *EEBUSServiceHandler {
	mock := &EEBUSServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
