// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SmartEnergyManagementPsServerInterface is an autogenerated mock type for the SmartEnergyManagementPsServerInterface type
type SmartEnergyManagementPsServerInterface struct {
	mock.Mock
}

type SmartEnergyManagementPsServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *SmartEnergyManagementPsServerInterface) EXPECT() *SmartEnergyManagementPsServerInterface_Expecter {
	return &SmartEnergyManagementPsServerInterface_Expecter{mock: &_m.Mock}
}

// NewSmartEnergyManagementPsServerInterface creates a new instance of SmartEnergyManagementPsServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSmartEnergyManagementPsServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SmartEnergyManagementPsServerInterface {
	mock := &SmartEnergyManagementPsServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
