// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TimeSeriesServerInterface is an autogenerated mock type for the TimeSeriesServerInterface type
type TimeSeriesServerInterface struct {
	mock.Mock
}

type TimeSeriesServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *TimeSeriesServerInterface) EXPECT() *TimeSeriesServerInterface_Expecter {
	return &TimeSeriesServerInterface_Expecter{mock: &_m.Mock}
}

// NewTimeSeriesServerInterface creates a new instance of TimeSeriesServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeSeriesServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeSeriesServerInterface {
	mock := &TimeSeriesServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
