// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/DerAndereAndi/eebus-go/spine/model"
	mock "github.com/stretchr/testify/mock"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Notify provides a mock function with given fields: senderAddress, destinationAddress, cmd
func (_m *Sender) Notify(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, cmd []model.CmdType) error {
	ret := _m.Called(senderAddress, destinationAddress, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, []model.CmdType) error); ok {
		r0 = rf(senderAddress, destinationAddress, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reply provides a mock function with given fields: requestHeader, senderAddress, cmd
func (_m *Sender) Reply(requestHeader *model.HeaderType, senderAddress *model.FeatureAddressType, cmd model.CmdType) error {
	ret := _m.Called(requestHeader, senderAddress, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.HeaderType, *model.FeatureAddressType, model.CmdType) error); ok {
		r0 = rf(requestHeader, senderAddress, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Request provides a mock function with given fields: cmdClassifier, senderAddress, ackRequest, cmd
func (_m *Sender) Request(cmdClassifier model.CmdClassifierType, senderAddress *model.FeatureAddressType, ackRequest bool, cmd []model.CmdType) (*model.MsgCounterType, error) {
	ret := _m.Called(cmdClassifier, senderAddress, ackRequest, cmd)

	var r0 *model.MsgCounterType
	if rf, ok := ret.Get(0).(func(model.CmdClassifierType, *model.FeatureAddressType, bool, []model.CmdType) *model.MsgCounterType); ok {
		r0 = rf(cmdClassifier, senderAddress, ackRequest, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.CmdClassifierType, *model.FeatureAddressType, bool, []model.CmdType) error); ok {
		r1 = rf(cmdClassifier, senderAddress, ackRequest, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendAcknowledgementMessage provides a mock function with given fields: err, featureSource, featureDestination, msgCounterReference
func (_m *Sender) SendAcknowledgementMessage(err error, featureSource *model.FeatureAddressType, featureDestination *model.FeatureAddressType, msgCounterReference *model.MsgCounterType) error {
	ret := _m.Called(err, featureSource, featureDestination, msgCounterReference)

	var r0 error
	if rf, ok := ret.Get(0).(func(error, *model.FeatureAddressType, *model.FeatureAddressType, *model.MsgCounterType) error); ok {
		r0 = rf(err, featureSource, featureDestination, msgCounterReference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: senderAddress, destinationAddress, serverFeatureType
func (_m *Sender) Subscribe(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, serverFeatureType model.FeatureTypeType) error {
	ret := _m.Called(senderAddress, destinationAddress, serverFeatureType)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) error); ok {
		r0 = rf(senderAddress, destinationAddress, serverFeatureType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
