// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	model "github.com/enbility/eebus-go/spine/model"
	mock "github.com/stretchr/testify/mock"

	spine "github.com/enbility/eebus-go/spine"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Bind provides a mock function with given fields: senderAddress, destinationAddress, serverFeatureType
func (_m *Sender) Bind(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, serverFeatureType model.FeatureTypeType) (*model.MsgCounterType, error) {
	ret := _m.Called(senderAddress, destinationAddress, serverFeatureType)

	var r0 *model.MsgCounterType
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) (*model.MsgCounterType, error)); ok {
		return rf(senderAddress, destinationAddress, serverFeatureType)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) *model.MsgCounterType); ok {
		r0 = rf(senderAddress, destinationAddress, serverFeatureType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) error); ok {
		r1 = rf(senderAddress, destinationAddress, serverFeatureType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DatagramForMsgCounter provides a mock function with given fields: msgCounter
func (_m *Sender) DatagramForMsgCounter(msgCounter model.MsgCounterType) (model.DatagramType, error) {
	ret := _m.Called(msgCounter)

	var r0 model.DatagramType
	var r1 error
	if rf, ok := ret.Get(0).(func(model.MsgCounterType) (model.DatagramType, error)); ok {
		return rf(msgCounter)
	}
	if rf, ok := ret.Get(0).(func(model.MsgCounterType) model.DatagramType); ok {
		r0 = rf(msgCounter)
	} else {
		r0 = ret.Get(0).(model.DatagramType)
	}

	if rf, ok := ret.Get(1).(func(model.MsgCounterType) error); ok {
		r1 = rf(msgCounter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Notify provides a mock function with given fields: senderAddress, destinationAddress, cmd
func (_m *Sender) Notify(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, cmd model.CmdType) (*model.MsgCounterType, error) {
	ret := _m.Called(senderAddress, destinationAddress, cmd)

	var r0 *model.MsgCounterType
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) (*model.MsgCounterType, error)); ok {
		return rf(senderAddress, destinationAddress, cmd)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) *model.MsgCounterType); ok {
		r0 = rf(senderAddress, destinationAddress, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) error); ok {
		r1 = rf(senderAddress, destinationAddress, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reply provides a mock function with given fields: requestHeader, senderAddress, cmd
func (_m *Sender) Reply(requestHeader *model.HeaderType, senderAddress *model.FeatureAddressType, cmd model.CmdType) error {
	ret := _m.Called(requestHeader, senderAddress, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.HeaderType, *model.FeatureAddressType, model.CmdType) error); ok {
		r0 = rf(requestHeader, senderAddress, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Request provides a mock function with given fields: cmdClassifier, senderAddress, destinationAddress, ackRequest, cmd
func (_m *Sender) Request(cmdClassifier model.CmdClassifierType, senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, ackRequest bool, cmd []model.CmdType) (*model.MsgCounterType, error) {
	ret := _m.Called(cmdClassifier, senderAddress, destinationAddress, ackRequest, cmd)

	var r0 *model.MsgCounterType
	var r1 error
	if rf, ok := ret.Get(0).(func(model.CmdClassifierType, *model.FeatureAddressType, *model.FeatureAddressType, bool, []model.CmdType) (*model.MsgCounterType, error)); ok {
		return rf(cmdClassifier, senderAddress, destinationAddress, ackRequest, cmd)
	}
	if rf, ok := ret.Get(0).(func(model.CmdClassifierType, *model.FeatureAddressType, *model.FeatureAddressType, bool, []model.CmdType) *model.MsgCounterType); ok {
		r0 = rf(cmdClassifier, senderAddress, destinationAddress, ackRequest, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(model.CmdClassifierType, *model.FeatureAddressType, *model.FeatureAddressType, bool, []model.CmdType) error); ok {
		r1 = rf(cmdClassifier, senderAddress, destinationAddress, ackRequest, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResultError provides a mock function with given fields: requestHeader, senderAddress, err
func (_m *Sender) ResultError(requestHeader *model.HeaderType, senderAddress *model.FeatureAddressType, err *spine.ErrorType) error {
	ret := _m.Called(requestHeader, senderAddress, err)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.HeaderType, *model.FeatureAddressType, *spine.ErrorType) error); ok {
		r0 = rf(requestHeader, senderAddress, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResultSuccess provides a mock function with given fields: requestHeader, senderAddress
func (_m *Sender) ResultSuccess(requestHeader *model.HeaderType, senderAddress *model.FeatureAddressType) error {
	ret := _m.Called(requestHeader, senderAddress)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.HeaderType, *model.FeatureAddressType) error); ok {
		r0 = rf(requestHeader, senderAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: senderAddress, destinationAddress, serverFeatureType
func (_m *Sender) Subscribe(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, serverFeatureType model.FeatureTypeType) (*model.MsgCounterType, error) {
	ret := _m.Called(senderAddress, destinationAddress, serverFeatureType)

	var r0 *model.MsgCounterType
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) (*model.MsgCounterType, error)); ok {
		return rf(senderAddress, destinationAddress, serverFeatureType)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) *model.MsgCounterType); ok {
		r0 = rf(senderAddress, destinationAddress, serverFeatureType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.FeatureTypeType) error); ok {
		r1 = rf(senderAddress, destinationAddress, serverFeatureType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: senderAddress, destinationAddress, cmd
func (_m *Sender) Write(senderAddress *model.FeatureAddressType, destinationAddress *model.FeatureAddressType, cmd model.CmdType) (*model.MsgCounterType, error) {
	ret := _m.Called(senderAddress, destinationAddress, cmd)

	var r0 *model.MsgCounterType
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) (*model.MsgCounterType, error)); ok {
		return rf(senderAddress, destinationAddress, cmd)
	}
	if rf, ok := ret.Get(0).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) *model.MsgCounterType); ok {
		r0 = rf(senderAddress, destinationAddress, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MsgCounterType)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.FeatureAddressType, *model.FeatureAddressType, model.CmdType) error); ok {
		r1 = rf(senderAddress, destinationAddress, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
